language: go

go:
- "1.17.6"

git:
  depth: 1

notifications:
  email: false

before_install:
- go install github.com/mattn/goveralls@v0.0.11

script:
- make lint
- make test
- $GOPATH/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
