language: go

go:
- "1.17.6"

git:
  depth: 1

notifications:
  email: false

before_install:
- "[ ! -z $COVERALLS_TOKEN ] && go install github.com/mattn/goveralls@v0.0.11"

script:
- "make lint"
- "make test"
- "[ ! -z $COVERALLS_TOKEN ] && $GOPATH/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN"
