language: go

go:
- "1.17.8"

git:
  depth: 1

notifications:
  email: false

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make test
    - stage: generate
      script: make check.generate
    - before_install: go install github.com/mattn/goveralls@v0.0.11
      script: $GOPATH/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
      if: branch = main