# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gherkingen < Formula
  desc "BDD tests boilerplate generator for Golang"
  homepage "https://github.com/hedhyw/gherkingen"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hedhyw/gherkingen/releases/download/v1.0.1/gherkingen_darwin_arm64.tar.gz"
      sha256 "23b96e1d7ea2a5f861c7b2f8f54967f12f1315d09c540de93a33811310de97a2"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/gherkingen/releases/download/v1.0.1/gherkingen_darwin_amd64.tar.gz"
      sha256 "4a0f1934fa5c8ef7f8184556fc1868f088ce3e1ff9a58d77d53de8b7cf6a984d"

      def install
        bin.install "gherkingen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hedhyw/gherkingen/releases/download/v1.0.1/gherkingen_linux_amd64.tar.gz"
      sha256 "f8df9965662a8bc705042ed29b3a3e43b993fd5309d0f432e793b69898e11923"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/gherkingen/releases/download/v1.0.1/gherkingen_linux_arm.tar.gz"
      sha256 "be9358fc9e15d94787ce2599ee98072860aa9327ed00955dc43fae721e76eb98"

      def install
        bin.install "gherkingen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hedhyw/gherkingen/releases/download/v1.0.1/gherkingen_linux_arm64.tar.gz"
      sha256 "bf0f4a2076385785b4168c5ad8e80e166d8d2a0449e57a10acb770ad88eb464a"

      def install
        bin.install "gherkingen"
      end
    end
  end

  test do
    system "#{bin}/gherkingen", "-help"
  end
end
