name: check-gherkingen

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.8'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Check generate
        run: make check.generate

      - name: Test
        run: make test

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
